### ISSUE TITLE
Neoforge 1.20.4 Crash during loot generation

### ISSUE THREAD

**Issue by Saereth** [P3pp3rF1y/SophisticatedStorage#405] opened 2024-04-28 06:10 UTC
When looting chests out in the wild after adding sophisticated storage/core/backpacks today we're now getting server crashes when people loot things occasionally. Here is the server logfile, if there is anything else I can test or provide feel free to let me know. Ty!

Logfile: https://mclo.gs/uP0sYqi
MC version 1.20.4
Neoforge Version: 20.4.233

```
sophisticatedcore-1.20.4-0.6.21.608.jar
sophisticatedbackpacks-1.20.4-3.20.5.1048
sophisticatedstorage-1.20.4-0.10.21.790.jar
```

**Comment by P3pp3rF1y** [comment] 2024-04-28 08:00
This is actually caused by SB code, but I have the fix and going to release fixed build on CF shortly

**Comment by P3pp3rF1y** [comment] 2024-04-28 08:22
Fixed in latest SB release on CF

**Closed as completed by P3pp3rF1y** 2024-04-28 08:22 UTC
