### ISSUE TITLE
Storage Item Icon Blacked Out on 1.20.1-Forge: 47.2.0

### ISSUE THREAD

**Issue by FelineCinders** [P3pp3rF1y/SophisticatedStorage#425] opened 2024-05-25 10:45 UTC
Hi!

The storage icon is blacked out in my game. I've generated many worlds to track down the issue and it occurs even when only sophisticated storage, core and backpacks are enabled on a fresh world.

What I do: 

- Create a sophisticated oak barrel
- Place an item in the first slot (e.g. a wooden sword or a diamond)
- Enable the item icon in the storage settings
- I do not alter the colour
- I select the first slot

**Comment by P3pp3rF1y** [comment] 2024-05-26 11:23
Could you share screenshot of that? And what version is it? And you don't have anything like rubidium or embeddium installed right?

**Comment by FelineCinders** [comment] 2024-05-26 13:40
Will do! That would be the latest 1.20.1 version: 0.10.25.804

This is issue occurs with or without any other mods installed. Even on fresh worlds that never had any mods installed.

This here is a diamond:

![2024-05-26_15 37 00](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/118782065/ce408bf8-f706-4069-b220-1abb4f58fc75)

**Comment by P3pp3rF1y** [comment] 2024-05-28 16:14
I am guessing you have smooth lighting off, right? This is what happens with smooth lighting off now that there is ambient occlusion for the block.

**Comment by P3pp3rF1y** [comment] 2024-09-20 23:57
I am pretty sure this is caused by smooth lighting off so closing.

**Closed as completed by P3pp3rF1y** 2024-09-20 23:57 UTC
