### ISSUE TITLE
Tabs keep closing after an interaction & inventory  and storage quantity invisible

### ISSUE THREAD

**Issue by VallenFrostweaver** [P3pp3rF1y/SophisticatedStorage#6] opened 2022-05-09 11:40 UTC
Minecraft 1.18.2
Forge 40.1.0
Sophisticated Storage 0.0.4.11
Sophisticated Core 0.0.5.12

When I use many uogrades (I'll use the crafting upgrade in this example) when placing an item in the crafting grid the tab closes instantly. I click to reopen the tab and an item has been placed but then I need to repeat it again and again until I have all the items in the crafting grid. This is the same behavior for many of the tabs. They keep closing once interacted with.

Perhaps along the same vein is when clicking the settings tab the player inventory contents is invisible but the inventory screen is still there and the storage quantity display is removed (instead of a stack of planks I see an image of a plank and no number over it). Not sure if this second thing is related to the first but it is only during tab interaction.

**Comment by metalim** [comment] 2022-05-10 11:40
[video capture](https://gfycat.com/jaggeddefenselesshalcyon)
it's a little bit worse than just closing once. Items are stuck in the upgrade, can't craft, nor take them out.

Sophisticated Storage 0.0.6.16
Sophisticated Core 0.0.7.16
Minecraft 1.18.2
Forge 40.1.19

(modpack: ATM7 0.3.22)

**Comment by P3pp3rF1y** [comment] 2022-05-10 18:00
Fixed in the latest release on curseforge

**Closed as completed by P3pp3rF1y** 2022-05-10 18:00 UTC

**Comment by P3pp3rF1y** [comment] 2022-05-11 16:30
@VallenFrostweaver Just a note on the second part of your issue which I skipped over previously. The missing inventory counts and player's inventory is by design - in settings view there isn't supposed to be an interaction with actual slot contents happening so only items are shown to help player with selecting the correct slots for e.g. memorized slots or slots that are not supposed to sort.
