### ISSUE TITLE
flatten/unflatten barrel recipe

### ISSUE THREAD

**Issue by AlleCraft-alterego** [P3pp3rF1y/SophisticatedStorage#176] opened 2023-05-06 04:29 UTC
i use limited barrel how storage for use structured crafting but with new conversion recipe, consume barrel for change flatten/unflatten barrel.... well i need remove/change this recipe of conversion, but cannot possible... can be add a method for change/remove this conversion recipe ? and a method to change all recipe of mod ? (for now ony existing datapack recipe can be changed)

**Comment by P3pp3rF1y** [comment] 2023-05-06 09:09
Sorry but I am not following the question/suggestion. Are you suggesting that you're using just a barrel in a recipe to craft something else? And why wouldn't it be possible to change that recipe into something that requires an additional item in the recipe?

**Comment by AlleCraft-alterego** [comment] 2023-05-06 21:37
the problem is the custom type of recipe cannot possible to change/remove like all auto generated crafting upgrade of all cherst/barrel/limited barrel and shulker box

**Comment by P3pp3rF1y** [comment] 2023-05-07 09:39
again, why do you need to remove the recipe? are you not happy that players are able to flatten the barrel?
the only reason I can find that you would want to remove it is because you want to have a recipe that only includes barrel and nothing else as ingredient, but I am finding it very hard to figure out why you would want that and why it would be impossible to add something to that recipe to make it work and keep the flatten recipe in place as is.

**Comment by AlleCraft-alterego** [comment] 2023-05-07 20:15
the problem is unchangable recipes, if i need change iron ingot on iron chest/all storage recipe cannot possible... and cannot disable recipe with data (only config) but the problem with barrel recipe for me is this: 

https://user-images.githubusercontent.com/72225590/236700558-9e0cbdff-11d8-47f8-87ac-fbd9e38443de.mp4

**Comment by P3pp3rF1y** [comment] 2023-05-07 22:11
Even with that video I don't completely understand what the issue is but it looks like that crafter isn't supposed to craft using those barrels in a recipe? Sounds like an issue with that mod as that means that any storage that has a recipe like this (e.g. quark chest to vanilla chest) will have the same issue. And the other thing is this dynamic recipe should still be disablable as any other recipe as it requires recipe json file for it to be registered so you should be able to use your tool of choice to remove `sophisticatedstorage:flat_top_barrel_toggle`. I don't really see anything else that would need to be done on my side so I am closing this now.

**Closed as completed by P3pp3rF1y** 2023-05-07 22:11 UTC
Labels: question

**Comment by AlleCraft-alterego** [comment] 2023-05-07 22:54
true, with quark there would be the same problem... but with quark I can modify the recipes as I like, for example, to convert a chest you have to put a stick together with the chest you want to convert, but your recipe is not vanilla but it's custom, so I want to understand how to modify it in order to add an object to the recipe to avoid the problem, and add the gamestage to be able to block the recipes of the various storage tiers.

**Comment by P3pp3rF1y** [comment] 2023-05-07 23:08
well as said the recipe needs to register for it to work so you can remove it using something like crafttweaker or kubejs. Even if I added possibility to change the recipe it would still be a custom recipe and not vanilla shaped or shapeless one
