### ISSUE TITLE
[1.20.1] Hopper upgrade crash

### ISSUE THREAD

**Issue by Arman20004** [P3pp3rF1y/SophisticatedStorage#422] opened 2024-05-21 09:22 UTC
I was playing on skyblock and noticed that if you place storage of any kind with hopper upgrade at lowest level facing into the void your game just crashes

**Comment by P3pp3rF1y** [comment] 2024-05-21 14:03
Could you share the crash log?

**Comment by Arman20004** [comment] 2024-05-21 15:31
Link to crash log:

https://mclo.gs/Sr1ndp5

**Comment by jammer312** [comment] 2024-08-29 21:52
Also happened to me today on a server. I've placed a chest at the lowest level in the end and slotted an advanced hopper upgrade into it, and right after that the server crashed, and whenever I joined it crashed again. I tried to reproduce it in singleplayer in overworld, but it didn't lead to a crash, so it might be that it only affects servers

**Comment by jammer312** [comment] 2024-08-29 21:58
https://pastebin.com/04pxYgB6 relevant crash log
I bet it's because the upgrade tries to access a block outside of world boundaries (so I guess the same happens when you place a container with a hopper upgrade at the highest point of the world)

**Comment by P3pp3rF1y** [comment] 2024-09-30 19:28
This is fixed in the latest versions

**Closed as completed by P3pp3rF1y** 2024-09-30 19:28 UTC
Labels: question
