### ISSUE TITLE
Crash on 1.19.2

### ISSUE THREAD

**Issue by Saereth** [P3pp3rF1y/SophisticatedStorage#91] opened 2022-10-26 17:20 UTC
Forge: 43.1.43
Loading up the pack, added in sophisticated backpacks and now I'm getting this crash

https://gist.github.com/Saereth/9204a542c98b28328dd108c5ad5dc01f

Let me know if you need any other info, thank you

**Comment by P3pp3rF1y** [comment] 2022-11-27 23:24
I am really not sure why this is happening for you, I can't recreate and judging by the fact that no one else has reported it seems to be specific to your pack. Are you able to recreate just with sophisticated mods?

**Comment by Nachtflame** [comment] 2023-03-25 00:49
Also been having this issue. But it's intermittent, and only happens every few loads, so I ignored it figuring someone else *must have* reported it 🤦‍♂️.  

Crashlog from minutes before this post: https://pastebin.com/4gd1Q6pS
Crashlog from last October when I first started experiencing the issue, with a different pack I was making: https://pastebin.com/11RJu3tJ

**Comment by Nachtflame** [comment] 2023-03-25 16:21
Loaded 10 times with _just_ Sophisticated mods - Failed to reproduce crash
Loaded 10+ times with Sophisticated mods & other mods used in my packs & Saraeth's - Failed to reproduce crash

Was loading with forge-43.2.8 (which I've experienced the crash on when _not_ trying to reproduce it).

Even had the thought to try with lower-ram (down to 1GB), and still unable to force the crash.

🤷‍♂️ Really not sure what to do at this point other than share the piles of logs I _do have_ from previous crashes, but that's _alot_ of crash reports.  
79 to be exact - [SophStorage_crash-logs.zip](https://github.com/P3pp3rF1y/SophisticatedStorage/files/11069386/SophStorage_crash-logs.zip)

**Comment by P3pp3rF1y** [comment] 2023-07-18 22:27
This logic was refactored to more standard model loading in the meantime and the code where it failed doesn't exist anymore. So I am closing and if something similar happens feel free to open a new ticket for that.

**Closed as completed by P3pp3rF1y** 2023-07-18 22:27 UTC
Labels: question
