### ISSUE TITLE
Storage controller recognized containers erroneously after rebooting the game.

### ISSUE THREAD

**Issue by codexyster** [P3pp3rF1y/SophisticatedStorage#286] opened 2023-09-08 02:08 UTC
I am not sure if this is caused by interaction with mod or other mods, here is the issue:

First, the whole system works find after I completely remake it. Then I quit the game and reboot it.

Here is the whole system after rebooting the game. The netherite barrel with order 1 has many carrots in it.
![2023-09-08_01 03 47](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/59946431/c85a0e00-32c6-4668-94c7-f78ddfaf3ca7)

This is a gold barrel that do not link to the whole system, with an enderbag (from ender storage mod. Ender storage is not part of the system or linked in any way. In this scenario it is just an item stored in the barrel.) in it 
![2023-09-08_01 03 49](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/59946431/ef3fb996-e63f-4717-ace0-09a70dd11f55)

Then, I double tap the storage controller, which should store all my carrots (hotbar 7) and leave the enderbad (hotbar 6) intact. But instead, the carrots are not taken into the netherite barrel, and my ender bag is taken into the gold barrel.
![2023-09-08_01 04 03](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/59946431/b29e112e-2a54-4179-b990-6af9c4d665c0)

This is the point when I know the whole system is broken. From a gui provide by simple storage network, all items from the netherite barrel are included in the network, but the item pattern is not, and vice versa for the gold barrel. (To be more specific, I can extract items like carrots from the netherite barrel through SSN gui, but when I try to put carrots back, the storage controller does not consider the netherite barrel a part of storage system and put it in other chest like the carrots are not in the system. Vice versa for the gold barrel beneath it. I can't extract items from it as they are not shown in the SSN gui, but when items are input, the gold barrel is considered a part of storage system, and the input item can be distributed into it.)

When the system is broken, save and quit the world leads to a crash. I don't know if this is relevant but here is the log.
[crash-2023-09-08_01.06.17-client.txt](https://github.com/P3pp3rF1y/SophisticatedStorage/files/12554715/crash-2023-09-08_01.06.17-client.txt)

If I completely rebuild the system by replacing controller and making a new netherite barrel to replace the old one, everything works fine and quitting the world won't crash the game. 

I am sorry for such a long and kinda confusing description. I would have tested it more in a less modded game environment if I got more free time. 

Mod version:
sophisticatedcore-1.18.2-0.5.87.416
sophisticatedstorage-1.18.2-0.8.42.599

**Comment by codexyster** [comment] 2023-09-08 04:35
I think I found the cause of this bug. It seems that the advanced filter upgrade is to blame.

**Comment by P3pp3rF1y** [comment] 2023-09-08 07:30
what is advanced filter upgrade doing? you mean that if you link storage that's next to storage with advanced filter upgrade you are then able to insert items into that one using controller?

Or are you just referring to the fact that you were able to take some items out but not put them back into the same storage? depends on filter settings but yeah filter can do that if you set it to only allow extracting the item, but not inserting.

**Comment by P3pp3rF1y** [comment] 2023-09-08 07:32
and just checked that crash - that's some create render logic crashing and nowhere in the crash there's a mention of sophisticated so you will need to report that to create mod

**Comment by codexyster** [comment] 2023-09-08 09:41
> what is advanced filter upgrade doing? you mean that if you link storage that's next to storage with advanced filter upgrade you are then able to insert items into that one using controller?
> 
> Or are you just referring to the fact that you were able to take some items out but not put them back into the same storage? depends on filter settings but yeah filter can do that if you set it to only allow extracting the item, but not inserting.

The advanced filter upgrade was only used to filter white wools by tag and prevent them from pulling out by a create mod hopper. When the advanced filter upgrade was implemented in the netherite barrel, the Storage controller would recognize the netherite barrel erroneously as I described above (When the link between the netherite barrel and controller were just finished, everything was fine initially. After rebooting the game, the bug occurred). It is worth noting that the gold barrel in the pictures (which was not related to the advanced filter upgrade of the above netherite barrel) was not linked to the storage controller, but under this glitch circumstance, it was somehow partially linked, despite the debug tool did not indicate so. When I plugged the advanced filter upgrade out of the barrel, everything was fine no matter how many times I reboot the game. 

> and just checked that crash - that's some create render logic crashing and nowhere in the crash there's a mention of sophisticated so you will need to report that to create mod

I thought so myself, but it was just so coincidental that I thought it might be related. Thanks for clarifying.

Edit: formatting

**Comment by P3pp3rF1y** [comment] 2023-10-20 18:12
the only thought I have here is that the netherite barrel had hopper upgrade in it which automatically output to the barrel below because otherwise I don't know how the item would get in there if the barrel isn't linked to controller (and it definitely isn't given that it doesn't show with debug tool). If you can share the settings of filter upgrade / what upgrades and potentially settings you had in that netherite barrel I can try to figure out what happened there, but otherwise I fell like I can't do anything here.

**Comment by Sadragos** [comment] 2024-02-05 12:59
I have a similar issue with the Storage Controller: I've a Controller connected to several Limited Barrels (mostly without upgrades). When I first place the Controller and Barrels everything seems to be working, but after a reboot I can't insert Items into the Controller (neither by hand nor by hopper/pipe). When I use Jade too look at the Controller it shows all Items from the Controller correctly, however insertion is impossible despite enough space. 

I think it must have something todo with the Memory-Slots / Filters, as I have another Controller, that is linked to unfiltered Barrels and Chests and it does not have these issues.

I'm using sophisticatedstorage-1.20.1-0.8.68.692.jar

**Comment by P3pp3rF1y** [comment] 2024-09-30 19:57
closing given no additional info was provided and the "bug" with insertion is likely caused by some mod that adds data to stacks, but doesn't add it to all of them making the ones in barrels different from the ones in player's hand. I had a few reports of that happening in some packs.

**Closed as completed by P3pp3rF1y** 2024-09-30 19:57 UTC
Labels: question
