### ISSUE TITLE
Basic Tier Upgrade deletes Items

### ISSUE THREAD

**Issue by RyanC-1229** [P3pp3rF1y/SophisticatedStorage#386] opened 2024-03-22 15:26 UTC
## Describe the Bug:
So I used a Base storage upgrade on a Vanilla chest and it upgrades the chest and the one beside it went and opened the OG chest and it acted as a double chest though looked like a single one then went and opened the extra upgrade and it wouldn't open.
I then re-logged to see if it was a visual glitch and then the OG chest was back to normal and could open the other one but then all of it's content was deleted.

## How to Reproduce the Bug:
  1.  Craft "Basic Tier Upgrade"
  2.  Use Item on Vanilla Chest with another one to the side of it(left?)
  3.  Observe everything is broken
  
  ## Mod Version 0.10.11.766

**Comment by P3pp3rF1y** [comment] 2024-03-22 15:38
I am unable to recreate that - tried with single upgrade which has shown the appropriate message that I need 2 of them, tried upgrading on left side with the 2 when that worked correctly I tried upgrading on the right side with the 2 and that worked as well.

So I will need steps I can use to recreate or if you had an issue on upgrading I am guessing some error was logged in log so would be great if you could share that.

It's likely some interaction with another mod that's going wrong here.

**Comment by generikb** [comment] 2024-03-22 23:01
https://github.com/Generik-Packs/UG200_Public/issues/7 I added more screenshots to the issue on our github, I'm about to test it with an instance that *only* has Soph Storage, will let you know

**Comment by generikb** [comment] 2024-03-22 23:10
Yes, able to recreate it in an instance with only JEI and Sophisticated mods.

I think the key to the test is to have two *single* chests next to each other, not a double chest.

if you can't reproduce stop by my stream this weekend and I'll show ya.  Thanks P3pp3r!

**Comment by P3pp3rF1y** [comment] 2024-03-23 23:42
Thanks for all the additional info @generikb 

There's a new release with fix for this issue on curseforge so closing

**Closed as completed by P3pp3rF1y** 2024-03-23 23:42 UTC
Labels: question
