### ISSUE TITLE
Storage Controller not meshing with Limited Storage [1.20.1] [0.10.25.804] [Issue with Origins: Suspected]

### ISSUE THREAD

**Issue by Xinterp6196** [P3pp3rF1y/SophisticatedStorage#437] opened 2024-06-22 20:22 UTC
**Minecraft Version:** 1.20.1
**Forge:** 47.3.0
**Modpack:** [RPGCraft [FORGE] [Boosh Domain]](https://www.curseforge.com/minecraft/modpacks/rpgcraft-forge-boosh-domain)
**Mods in the pack:** See Spreadsheet [here](https://docs.google.com/spreadsheets/d/1wK7KjlSt82Ye705Sj2hXDhcpI5dai5yC-yKYiQJ6zXo/edit?gid=1547824501#gid=1547824501)

I'm having an issue where any and all drawers connected to the Storage Controller fail to work again after a server restart or you move away from the chunk where this system is at. I believe it's an interaction with the Advanced Hopper Upgrade and the Storage Controller.

This appears to happen both when Storage is Locked or Unlocked.

The current resolution to the issue is removing each item in each drawer, cycling each item with another item, then putting those items back. While this works, its more tedious than sorting normally with just your hands.

Storage Controller is linked currently to a Storage Link that's sitting on top of a line of Limited Storage Containers.

![2024-06-22_15 13 48](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/103495470/c029d2f6-f54a-4a05-938f-dc09c92e263c)
![2024-06-22_15 15 46](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/103495470/f92b0f5a-be24-432a-8e1d-4f5e9321d31a)
![2024-06-22_15 17 47](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/103495470/cf60bf57-cbc3-453c-aab2-7db1f679c505)

I hate to call this a bug, but I don't know what else could be causing this since no errors pop up. No crashes, no server errors, no client errors, nothing.

**Comment by Xinterp6196** [comment] 2024-06-22 21:54
I'll do additional testing tonight, but I believe this is with just the Advanced Hopper Upgrade. I'll test the normal one and get a more stable answer.

- Edit: That does not seem to be the issue. Its as if the Limited stuff appears to be "Forgetting" what was inside of it? Still no logs as its not causing a crash or error.

**Comment by P3pp3rF1y** [comment] 2024-06-24 06:13
I don't see a controller in those screenshots and I don't see what you're doing with that chest with hopper upgrade, could you show explain that?
Also I hope that chest isn't connected to the multiblock because and isn't pushing into controller because in that case the chest itself is a valid target for the items that it tries to push because controller has a record of those items existing in it.

**Comment by Hubnester** [comment] 2024-06-25 10:33
I'm also getting a similar issue. The only upgrades in my limited storages are stack upgrades tier 1 plus (also occurs with no upgrades). Some things I've observed about it:
- When the limited storages have the issue it seems that no automation can insert into them (I've confirmed hoppers, the storage controller, pipez pipes, ars nouveau storage lectern and mana and artifice constructs can't add items hen the storage is in this state).
- Adding or removing a stack upgrade seems to be enough to fix them until the issue triggers again.
- If an ars nouveau storage lectern is connected to a limited storage the issue doesn't seem to trigger (unless it is also connected to a storage controller)

**Comment by Xinterp6196** [comment] 2024-06-25 19:32
> I don't see a controller in those screenshots and I don't see what you're doing with that chest with hopper upgrade, could you show explain that? Also I hope that chest isn't connected to the multiblock because and isn't pushing into controller because in that case the chest itself is a valid target for the items that it tries to push because controller has a record of those items existing in it.

Absolutely. Didn't mean to mislead you.
The Storage Controller is directly below the chest with the Hopper upgrade.
Crouch Right Clicked the chest onto the Storage Controller as I've done before with previous versions.

The chest is supposed to act as a sorting medium for us on our multiplayer server. Lots of people dump items in or place backpacks on top of it. It filters out items into the chest that don't go into auto-sort, and we can extract to the back of the chest to a backpack for the items that don't filter into the system. The chest is locked which shouldn't allow for the controller to put anything into it.

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/103495470/badedcea-fda3-4bbb-b8ee-91031d849789)

Here is the reference image with Storage Drawers instead of Sophisticated Storage. Grey Wool is an output and so is the bottom of the chest. All other sides are inputs.

I will say that this was happening before with an actual hopper acting as a medium between chest and the Storage Controller.

**Comment by P3pp3rF1y** [comment] 2024-06-26 19:17
@Xinterp6196  if you had Sophisticated storage setup this way then the results you are seeing are expected - chest is touching controller so it gets connected and becomes one of the storages that are a valid target for controller to put stuff into. And actually the backpack will get added to the multiblock as well because the chest below it is part of the multiblock. 
And when these are connected and chest tries to push stuff into controller the controller then tries to find usually the closest storage for stuff that chest is pushing into it and because the chest is closest it will get put back into it. So the hopper upgrade is actually working but stacks end up in the same place. You will want to use storage input for this kind of setup because that block doesn't connect storage blocks to the multiblock.

**Comment by P3pp3rF1y** [comment] 2024-06-26 19:19
@Hubnester you have steps I can go through to try to recreate your issue where storage blocks can't be inserted into at all? And are you sure they are not locked or that you have an item in them that you are trying to insert in (and pipes are able to match) if they are?

**Comment by Xinterp6196** [comment] 2024-06-26 20:17
> @Xinterp6196 if you had Sophisticated storage setup this way then the results you are seeing are expected - chest is touching controller so it gets connected and becomes one of the storages that are a valid target for controller to put stuff into. And actually the backpack will get added to the multiblock as well because the chest below it is part of the multiblock. And when these are connected and chest tries to push stuff into controller the controller then tries to find usually the closest storage for stuff that chest is pushing into it and because the chest is closest it will get put back into it. So the hopper upgrade is actually working but stacks end up in the same place. You will want to use storage input for this kind of setup because that block doesn't connect storage blocks to the multiblock.

Thank you for the info. Feel free to close this one. Just PEBKAC/User Error.
Disregard this. Origins and Sophisticated Storage appear to be conflicting somehow.

**Comment by Hubnester** [comment] 2024-06-27 02:45
> @Hubnester you have steps I can go through to try to recreate your issue where storage blocks can't be inserted into at all? And are you sure they are not locked or that you have an item in them that you are trying to insert in (and pipes are able to match) if they are?

Forge Version: 47.2.0
Modlist: https://pastebin.com/kSKUuLbP

Steps to reproduce:
1. Place limited barrel and hopper down next to it (or any method of inserting items)
2. Put items in barrel
3. Remove some of the items from the barrel so that you know for sure that they are ones that can be inserted
4. Go away from the area it is in for a bit (pretty sure the chunk needs to stop being loaded, might not happen every time) or restart the server/world
5. Put the items you removed earlier into the hopper
6. Observe that they don't get inserted

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/31746595/4680b77a-571c-4da9-913e-3eb9ba491491)
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/31746595/04597a64-4a43-4030-9af6-a8d183c5d215)

I've also noticed that it seems to also affect the normal sophisticated storage barrels (if you try inserting items into them after doing the above steps, it will put them in new stacks even if the stack isn't full)
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/31746595/1ab6768b-c799-4c6e-8de0-b6fc31891ab5)

**Comment by P3pp3rF1y** [comment] 2024-06-27 07:38
@Hubnester I am unable to recreate it, whatever I try the hopper just keeps working properly so there's something more involved here or a mod is making changes to hopper / item piping that causes this. If you are able to narrow it down to minimal set of mods I can take one more look. Judging by the fact that storage is used a lot and this is the only report I have on an issue like that it must be mod that's not used commonly. Or another idea I have is potentially this could be caused by custom server implementations if you are running this on a server and it's not just the base forge / neoforge

**Comment by Hubnester** [comment] 2024-06-27 12:16
> @Hubnester I am unable to recreate it, whatever I try the hopper just keeps working properly so there's something more involved here or a mod is making changes to hopper / item piping that causes this. If you are able to narrow it down to minimal set of mods I can take one more look. Judging by the fact that storage is used a lot and this is the only report I have on an issue like that it must be mod that's not used commonly. Or another idea I have is potentially this could be caused by custom server implementations if you are running this on a server and it's not just the base forge / neoforge

Looks like it's caused by Origins (forge). The issue occurs with this modlist: https://pastebin.com/6tgG2xEF

**Comment by Xinterp6196** [comment] 2024-06-30 05:18
> Looks like it's caused by Origins (forge). The issue occurs with this modlist: https://pastebin.com/6tgG2xEF

Do you happen to have the log where the error happens? We are also running Origins.

Here is our latest server log from [MCLOGS](https://mclo.gs/ImlfDxe)
Here is a Critical unrelated error [PASTEBIN](https://pastebin.com/ezPinBrM)

**Comment by P3pp3rF1y** [comment] 2024-09-21 10:46
So this issue is caused by origins attaching capabilities to stacks, but somehow they are not attaching them to stacks when they get loaded from nbt. Because this is done as part of some closed source Apoli library there's not much else I can do here other than close as something that needs to be fixed on their side.

**Closed as completed by P3pp3rF1y** 2024-09-21 10:46 UTC
